name: "butfly"

services:
  butfly-api:
    build: .
    container_name: butfly-api
    restart: always
    volumes:
    - .:/usr/app
    depends_on:
      butfly-database:
        condition: service_healthy
    ports:
      - 3333:3333
    env_file:
      - ./.env.dev
    depends_on:
      - butfly-database

  butfly-database:
    image: postgres:latest
    container_name: butfly-database
    restart: always
    ports:
      - 5400:5432
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=root
      - POSTGRES_DB=butfly

  butfly-testing:
    image: postgres:latest
    container_name: butfly-testing
    restart: always
    ports:
      - 5401:5432
    environment:
      - POSTGRES_PASSWORD=Butfly123
      - POSTGRES_USER=user
      - POSTGRES_DB=testing
