version: "3.9"
name: "butfly"

services:
  butfly-api:
    container_name: butfly-api
    build: .
    restart: always
    volumes:
      - .:/usr/app
    ports:
      - 3333:3333

  butfly-database:
    image: postgres:latest
    container_name: butfly-database
    restart: always
    ports:
      - 5400:5432
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=root
      - POSTGRES_DB=butfly

  butfly-testing:
    image: postgres:latest
    container_name: butfly-testing
    restart: always
    ports:
      - 5401:5432
    environment:
      - POSTGRES_PASSWORD=Butfly123
      - POSTGRES_USER=user
      - POSTGRES_DB=testing
