version: "3.9"
name: "butfly"

networks:
  butfly:
    driver: bridge

services:
  butfly-database:
    image: postgres:latest
    container_name: butfly-database
    restart: unless-stopped
    networks:
      - butfly
    ports:
      - 5400:5432
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=root
      - POSTGRES_DB=butfly

  butfly-testing:
    image: postgres:latest
    container_name: butfly-testing
    restart: unless-stopped
    networks:
      - butfly
    ports:
      - 5401:5432
    environment:
      - POSTGRES_PASSWORD=Butfly123
      - POSTGRES_USER=user
      - POSTGRES_DB=testing
