version: 2.1
orbs:
  node: circleci/node@4.7

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:2022.04.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Install postgres
          command: docker-compose up
      - run:
          name: Create .env
          command: echo "DATABASE_URL=" | tee .env
      - run:
          name: Run tests
          command: yarn test
workflows:
  production:
    jobs:
      - build-and-test
